Parameters:
  bucketname:
    Type: String
    Default: workshop.codebuild.cloudformation
Resources:
  CodebuildExample:
    Type: "AWS::CodeBuild::Project"
    Properties: 
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Descrizione
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: EnvName
            Value: EnvValue
        Image: aws/codebuild/docker:1.12.1
      Name: Codebuild-example
      ServiceRole: !Ref CodeBuildServiceRole
      Source:
        Location: !Sub ${bucketname}/source.zip
        Type: "S3"
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - docker build .
            post_build:
              commands:
                - printf '{"tag":"%s"}' $TAG > build.json
          artifacts:
            files: build.json

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ecr:GetAuthorizationToken
              - Resource: !Sub arn:aws:s3:::*
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
              - Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:*
                Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
